# Generated by Django 5.1.5 on 2025-01-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
